(function () {
  "use strict";
  const STORAGE_KEY = "decilo-mvp-v1";
  const SESSION_KEY = "decilo-session-v1";
  const pictograms = [
    { id: "quiero", word: "Quiero", alt: "Mano abierta para expresar deseo", symbol: "🙋", category: "acciones", license: "DECILO inicial" },
    { id: "necesito", word: "Necesito", alt: "Mano levantada para pedir ayuda", symbol: "🤲", category: "acciones", license: "DECILO inicial" },
    { id: "comer", word: "Comer", alt: "Plato con cubiertos", symbol: "🍽️", category: "acciones", license: "DECILO inicial" },
    { id: "tomar", word: "Tomar", alt: "Vaso para beber", symbol: "🥤", category: "acciones", license: "DECILO inicial" },
    { id: "mama", word: "Mamá", alt: "Persona adulta cuidadora", symbol: "👩", category: "personas", license: "DECILO inicial" },
    { id: "papa", word: "Papá", alt: "Persona adulta cuidadora", symbol: "👨", category: "personas", license: "DECILO inicial" },
    { id: "galletita", word: "Galletita", alt: "Galletita redonda", symbol: "🍪", category: "comida", license: "DECILO inicial" },
    { id: "agua", word: "Agua", alt: "Vaso de agua", symbol: "💧", category: "comida", license: "DECILO inicial" },
    { id: "pelota", word: "Pelota", alt: "Pelota de colores", symbol: "⚽", category: "juguetes", license: "DECILO inicial" },
    { id: "musica", word: "Música", alt: "Nota musical", symbol: "🎵", category: "juguetes", license: "DECILO inicial" },
    { id: "feliz", word: "Feliz", alt: "Cara sonriente", symbol: "🙂", category: "emociones", license: "DECILO inicial" },
    { id: "cansado", word: "Cansado", alt: "Cara con expresión de cansancio", symbol: "😴", category: "emociones", license: "DECILO inicial" },
    { id: "hola", word: "Hola", alt: "Mano saludando", symbol: "👋", category: "social", license: "DECILO inicial" },
    { id: "gracias", word: "Gracias", alt: "Manos juntas para agradecer", symbol: "🙏", category: "social", license: "DECILO inicial" }
  ];
  const categories = ["todas", "acciones", "personas", "comida", "juguetes", "emociones", "social"];
  const categoryLabels = { todas: "Todos", acciones: "Acciones", personas: "Personas", comida: "Comida", juguetes: "Juguetes", emociones: "Emociones", social: "Social" };
  const roleLabels = { profesional: "Profesional", paciente: "Paciente", familiar: "Familiar" };
  const seed = {
    users: [
      { id: "prof-1", name: "Sofía Valenzuela", email: "sofia@decilo.test", role: "profesional", password: "decilo" },
      { id: "pac-1", name: "Mateo Gómez", email: "mateo@decilo.test", role: "paciente", password: "decilo" },
      { id: "fam-1", name: "Carla Gómez", email: "carla@decilo.test", role: "familiar", password: "decilo" }
    ],
    relationships: [{ professionalId: "prof-1", patientId: "pac-1", familyIds: ["fam-1"] }],
    boards: [{ id: "board-1", patientId: "pac-1", professionalId: "prof-1", name: "Comunicación cotidiana", pictogramIds: ["quiero", "necesito", "comer", "tomar", "galletita", "agua", "feliz", "hola", "gracias"] }],
    activities: [
      { id: "activity-1", patientId: "pac-1", professionalId: "prof-1", title: "Pedir la merienda", instruction: "Construir una frase con Quiero y un alimento antes de la merienda.", availability: "Hogar", points: 15, status: "available" },
      { id: "activity-2", patientId: "pac-1", professionalId: "prof-1", title: "Saludar al llegar", instruction: "Usar Hola y Gracias durante una interacción familiar.", availability: "Consulta", points: 10, status: "available" }
    ],
    deliveries: [], comments: [], badges: []
  };
  let data = loadData();
  let session = loadSession();
  let view = session ? (session.role === "paciente" ? "comunicador" : "inicio") : "login";
  let selectedRole = "profesional";
  let activePatientId = "pac-1";
  let phrase = [];
  let activeCategory = "todas";

  function clone(value) { return JSON.parse(JSON.stringify(value)); }
  function loadData() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || clone(seed); } catch (_) { return clone(seed); } }
  function loadSession() { try { return JSON.parse(sessionStorage.getItem(SESSION_KEY)); } catch (_) { return null; } }
  function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
  function announce(message) { document.getElementById("live-region").textContent = message; }
  function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char])); }
  function user() { return data.users.find((item) => item.id === session?.userId); }
  function relationshipFor(patientId) { return data.relationships.find((item) => item.patientId === patientId && (item.patientId === session?.userId || item.professionalId === session?.userId || item.familyIds.includes(session?.userId))); }
  function canAccessPatient(patientId) { return Boolean(session && relationshipFor(patientId)); }
  function patientsForCurrentUser() { if (!session) return []; if (session.role === "paciente") return data.users.filter((item) => item.id === session.userId); const ids = data.relationships.filter((item) => session.role === "profesional" ? item.professionalId === session.userId : item.familyIds.includes(session.userId)).map((item) => item.patientId); return data.users.filter((item) => ids.includes(item.id)); }
  function activitiesFor(patientId) { return canAccessPatient(patientId) ? data.activities.filter((item) => item.patientId === patientId) : []; }
  function deliveryFor(activityId) { return data.deliveries.find((item) => item.activityId === activityId); }
  function pointsFor(patientId) { return data.deliveries.filter((item) => item.patientId === patientId).reduce((sum, item) => sum + item.points, 0); }
  function badgesFor(patientId) { return data.badges.filter((item) => item.patientId === patientId); }
  function patientName(patientId) { return data.users.find((item) => item.id === patientId)?.name || "Paciente"; }
  function showToast(message) { const old = document.querySelector(".toast"); if (old) old.remove(); const toast = document.createElement("div"); toast.className = "toast"; toast.setAttribute("role", "status"); toast.textContent = message; document.body.appendChild(toast); setTimeout(() => toast.remove(), 3200); }

  function render() { document.getElementById("app").innerHTML = session ? renderApp() : renderLogin(); bindEvents(); }
  function renderLogin() { return `<main class="login-shell"><section class="login-card" aria-labelledby="login-title"><div class="brand-mark"><b aria-hidden="true">D</b><span>DECILO</span></div><p class="eyebrow" style="margin-top:28px">Comunicación que acompaña</p><h1 id="login-title">Un espacio para decir, practicar y compartir.</h1><p class="lead">Un MVP accesible para conectar la comunicación aumentativa con la práctica fonoaudiológica y el acompañamiento familiar.</p><form class="login-form" id="login-form"><fieldset style="border:0;padding:0;margin:0"><legend class="eyebrow">Elegí tu espacio</legend><div class="role-grid">${Object.entries(roleLabels).map(([role, label]) => `<button type="button" class="role-button" data-role="${role}" aria-pressed="${selectedRole === role}"><span class="role-icon" aria-hidden="true">${role === "profesional" ? "✦" : role === "paciente" ? "◉" : "⌂"}</span><strong>${label}</strong><span>${role === "profesional" ? "Configurar y acompañar" : role === "paciente" ? "Comunicar y practicar" : "Acompañar desde casa"}</span></button>`).join("")}</div></fieldset><label for="login-email">Correo de demostración<input id="login-email" name="email" type="email" value="${selectedRole === "profesional" ? "sofia@decilo.test" : selectedRole === "paciente" ? "mateo@decilo.test" : "carla@decilo.test"}" required /></label><label for="login-password">Clave<input id="login-password" name="password" type="password" value="decilo" required /></label><p class="hint">Demo local: la clave de los tres perfiles es <strong>decilo</strong>.</p><p id="login-message" class="message" role="alert"></p><button class="primary-button" type="submit">Entrar a DECILO</button></form></section></main>`; }
  function renderApp() { const current = user(); return `<header class="topbar"><div class="brand-mark"><b aria-hidden="true">D</b><span>DECILO</span></div><div class="topbar-actions"><span class="session-label">${escapeHtml(current.name)} · ${roleLabels[current.role]}</span><button class="icon-button" id="logout-button" title="Cerrar sesión" aria-label="Cerrar sesión">↪</button></div></header><div class="layout"><aside class="sidebar"><p class="eyebrow">Tu espacio</p><strong>${escapeHtml(current.name)}</strong><nav aria-label="Navegación principal">${navItems().map((item) => `<button class="nav-button" data-view="${item.id}" aria-current="${view === item.id ? "page" : "false"}">${item.label}</button>`).join("")}</nav><div class="section"><p class="hint">Los datos se guardan solo en este dispositivo durante el MVP.</p></div></aside><main class="content">${renderView()}</main></div>`; }
  function navItems() { if (session.role === "profesional") return [{ id: "inicio", label: "Resumen" }, { id: "pacientes", label: "Pacientes" }, { id: "tableros", label: "Tableros" }, { id: "actividades", label: "Actividades" }, { id: "progreso", label: "Progreso" }]; if (session.role === "paciente") return [{ id: "comunicador", label: "Mi comunicador" }, { id: "actividades", label: "Mis actividades" }, { id: "progreso", label: "Mis logros" }]; return [{ id: "inicio", label: "Seguimiento" }, { id: "actividades", label: "Actividades de hogar" }, { id: "progreso", label: "Comentarios" }]; }
  function heading(eyebrow, title, description, action = "") { return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div>${action}</div>`; }
  function renderView() { if (view === "comunicador") return renderCommunicator(); if (view === "pacientes") return renderPatients(); if (view === "tableros") return renderBoards(); if (view === "actividades") return renderActivities(); if (view === "progreso") return renderProgress(); return renderHome(); }
  function patientSelect() { const patients = patientsForCurrentUser(); return patients.length > 1 ? `<label>Paciente<select id="patient-select">${patients.map((item) => `<option value="${item.id}" ${activePatientId === item.id ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join("")}</select></label>` : ""; }
  function renderHome() { const patients = patientsForCurrentUser(); const activities = patients.flatMap((item) => activitiesFor(item.id)); const pending = activities.filter((item) => !deliveryFor(item.id)); return `${heading(session.role === "familiar" ? "Acompañamiento familiar" : "Sesión activa", session.role === "familiar" ? "Seguimiento que se puede compartir" : "Panel de acompañamiento", session.role === "familiar" ? "Consultá las actividades de hogar y mantené informado al equipo." : "Una vista clara para decidir qué necesita atención hoy.", session.role === "profesional" ? `<button class="primary-button" data-action="new-patient">Registrar paciente</button>` : "")}<section class="stats-grid"><article class="card"><span class="muted">Pacientes vinculados</span><strong class="stat-value">${patients.length}</strong><span class="status success">✓ Relación autorizada</span></article><article class="card"><span class="muted">Actividades pendientes</span><strong class="stat-value">${pending.length}</strong><span class="status pending">! Para revisar</span></article><article class="card"><span class="muted">Puntos acumulados</span><strong class="stat-value">${patients.reduce((sum, item) => sum + pointsFor(item.id), 0)}</strong><span class="status success">★ Recompensas idempotentes</span></article><article class="card"><span class="muted">Comentarios</span><strong class="stat-value">${data.comments.filter((item) => patients.some((patient) => patient.id === item.patientId)).length}</strong><span class="status pending">✎ Registro familiar</span></article></section><section class="section panel"><div class="section-heading"><div><h2>Personas y actividad reciente</h2><p class="muted">Solo aparecen relaciones que tu sesión puede consultar.</p></div></div>${patients.length ? `<div class="list">${patients.map((patient) => `<div class="list-item"><div><h3>${escapeHtml(patient.name)}</h3><p class="muted">${activitiesFor(patient.id).length} actividades · ${pointsFor(patient.id)} puntos · ${badgesFor(patient.id).length} insignias</p></div><button class="secondary-button" data-patient="${patient.id}" data-view="${session.role === "profesional" ? "progreso" : "actividades"}">Abrir seguimiento</button></div>`).join("")}</div>` : `<div class="empty">Todavía no hay pacientes vinculados a esta cuenta.</div>`}</section>`; }
  function renderPatients() { const patients = patientsForCurrentUser(); return `${heading("Gestión de relaciones", "Pacientes", "Registrá datos mínimos y mantené explícita cada vinculación.", `<button class="primary-button" data-action="new-patient">+ Nuevo paciente</button>`)}<section class="panel">${patients.length ? `<div class="list">${patients.map((patient) => `<div class="list-item"><div><h3>${escapeHtml(patient.name)}</h3><p class="muted">${escapeHtml(patient.email)} · ${activitiesFor(patient.id).length} actividades asignadas</p><span class="status success">✓ Vinculado a tu sesión</span></div><button class="secondary-button" data-patient="${patient.id}" data-view="progreso">Ver progreso</button></div>`).join("")}</div>` : `<div class="empty">No hay registros todavía.</div>`}</section>`; }
  function renderBoards() { const patients = patientsForCurrentUser(); const boards = data.boards.filter((board) => patients.some((patient) => patient.id === board.patientId)); return `${heading("Comunicación", "Tableros personalizados", "Ordená pictogramas para que cada paciente encuentre su voz.", `<button class="primary-button" data-action="new-board">+ Nuevo tablero</button>`)}<section class="card-grid">${boards.length ? boards.map((board) => `<article class="card"><p class="eyebrow">${escapeHtml(patientName(board.patientId))}</p><h3>${escapeHtml(board.name)}</h3><p class="muted">${board.pictogramIds.length} pictogramas en orden personalizado.</p><div class="button-row"><button class="secondary-button" data-board="${board.id}" data-action="edit-board">Editar tablero</button><span class="status success">✓ Compartido con el paciente</span></div></article>`).join("") : `<div class="empty full">Creá el primer tablero para comenzar.</div>`}</section>`; }
  function renderCommunicator() { const board = data.boards.find((item) => item.patientId === session.userId); const available = (board?.pictogramIds || []).map((id) => pictograms.find((item) => item.id === id)).filter(Boolean).filter((item) => activeCategory === "todas" || item.category === activeCategory); return `${heading("Comunicación aumentativa", "Mi frase, mi voz", "Tocá los pictogramas para construir una frase y reproducirla en tiempo real.", patientSelect())}<section class="board-strip" aria-labelledby="phrase-title"><div class="section-heading"><h2 id="phrase-title">Frase en construcción <span class="status pending">${phrase.length} palabras</span></h2></div><div class="phrase" aria-live="polite">${phrase.length ? phrase.map((item, index) => `<button class="phrase-token" data-phrase-index="${index}" title="Quitar ${escapeHtml(item.word)}"><span class="symbol" aria-hidden="true">${item.symbol}</span><span class="word">${escapeHtml(item.word)}</span></button>`).join("") : `<p class="phrase-empty">Elegí un pictograma del tablero para comenzar.</p>`}</div><div class="board-actions"><button class="primary-button" data-action="speak">▶ Reproducir frase</button><button class="secondary-button" data-action="undo" ${phrase.length ? "" : "disabled"}>↶ Deshacer</button><button class="danger-button" data-action="clear-phrase" ${phrase.length ? "" : "disabled"}>× Borrar frase</button></div><p id="speech-message" class="message" role="status"></p></section><section class="section"><div class="section-heading"><div><h2>Tablero de ${escapeHtml(board?.name || "comunicación")}</h2><p class="muted">Cada pictograma incluye texto asociado, descripción alternativa y metadato de licencia.</p></div></div><div class="category-tabs" role="tablist" aria-label="Categorías de pictogramas">${categories.map((category) => `<button class="category-tab" data-category="${category}" aria-selected="${activeCategory === category}">${categoryLabels[category]}</button>`).join("")}</div><div class="picto-grid" style="margin-top:18px">${available.length ? available.map((item) => `<button class="picto-tile" data-picto="${item.id}" aria-label="Agregar ${escapeHtml(item.word)}. ${escapeHtml(item.alt)}"><span class="symbol" aria-hidden="true">${item.symbol}</span><span class="word">${escapeHtml(item.word)}</span><span class="picto-meta">${categoryLabels[item.category]}</span></button>`).join("") : `<div class="empty full">${board ? "Este tablero no tiene pictogramas en esta categoría." : "Todavía no tenés un tablero asignado."}</div>`}</div></section>`; }
  function renderActivities() { const patients = patientsForCurrentUser(); const list = patients.flatMap((patient) => activitiesFor(patient.id).map((activity) => ({ ...activity, patientName: patient.name, delivery: deliveryFor(activity.id) }))); return `${heading(session.role === "paciente" ? "Práctica" : session.role === "familiar" ? "Rutinas en casa" : "Plan de trabajo", session.role === "paciente" ? "Mis actividades" : "Actividades asignadas", "Las entregas se conservan como historial y cada actividad suma puntos una sola vez.", session.role === "profesional" ? `<button class="primary-button" data-action="new-activity">+ Asignar actividad</button>` : "")}<section class="list panel">${list.length ? list.map((item) => `<article class="list-item"><div><p class="eyebrow">${escapeHtml(item.patientName)} · ${escapeHtml(item.availability)}</p><h3>${escapeHtml(item.title)}</h3><p class="muted">${escapeHtml(item.instruction)}</p><span class="status ${item.delivery ? "success" : "pending"}">${item.delivery ? `✓ Completada por ${item.delivery.origin === "familiar" ? "familiar" : "paciente"}` : `! Pendiente · ${item.points} puntos`}</span></div>${item.delivery ? `<span class="muted">${new Date(item.delivery.completedAt).toLocaleDateString("es-AR")}</span>` : session.role === "profesional" ? "" : `<button class="primary-button" data-complete="${item.id}">${session.role === "familiar" ? "Completar en casa" : "Marcar completada"}</button>`}</article>`).join("") : `<div class="empty">No hay actividades disponibles para esta sesión.</div>`}</section>`; }
  function renderProgress() { const patients = patientsForCurrentUser(); const patient = patients.find((item) => item.id === activePatientId) || patients[0]; if (!patient) return `${heading("Seguimiento", "Sin datos todavía", "Cuando exista una relación autorizada, el resumen aparecerá aquí.")}<div class="empty">No hay un paciente autorizado para mostrar.</div>`; const assigned = activitiesFor(patient.id); const completed = assigned.filter((item) => deliveryFor(item.id)); const comments = data.comments.filter((item) => item.patientId === patient.id); return `${heading("Seguimiento verificable", `Progreso de ${escapeHtml(patient.name)}`, "Totales derivados del historial de entregas, sin gráficos avanzados ni interpretaciones clínicas.", patientSelect())}<section class="stats-grid"><article class="card"><span class="muted">Asignadas</span><strong class="stat-value">${assigned.length}</strong><span class="status pending">! Plan actual</span></article><article class="card"><span class="muted">Completadas</span><strong class="stat-value">${completed.length}</strong><span class="status success">✓ Historial conservado</span></article><article class="card"><span class="muted">Puntos</span><strong class="stat-value">${pointsFor(patient.id)}</strong><span class="status success">★ Una vez por entrega</span></article><article class="card"><span class="muted">Insignias</span><strong class="stat-value">${badgesFor(patient.id).length}</strong><span class="status success">✓ Sin duplicados</span></article></section><section class="section card"><div class="section-heading"><h2>Avance básico</h2><span>${assigned.length ? Math.round(completed.length / assigned.length * 100) : 0}%</span></div><div class="progress-bar" aria-label="${completed.length} de ${assigned.length} actividades completadas"><span style="width:${assigned.length ? completed.length / assigned.length * 100 : 0}%"></span></div></section>${session.role === "familiar" ? `<section class="section panel"><h2>Enviar comentario al profesional</h2><form id="comment-form" class="form-grid"><label class="full" for="comment-text">Comentario<textarea id="comment-text" required minlength="3" placeholder="Contá cómo fue la práctica en casa."></textarea></label><button class="primary-button" type="submit">Guardar comentario</button></form></section>` : ""}<section class="section panel"><div class="section-heading"><h2>Comentarios compartidos</h2><span class="status pending">${comments.length} registrados</span></div>${comments.length ? `<div class="list">${comments.map((comment) => `<div class="list-item"><div><h3>${escapeHtml(comment.authorName)}</h3><p>${escapeHtml(comment.text)}</p></div><time class="muted" datetime="${comment.createdAt}">${new Date(comment.createdAt).toLocaleDateString("es-AR")}</time></div>`).join("")}</div>` : `<div class="empty">Todavía no hay comentarios para este paciente.</div>`}</section>`; }

  function bindEvents() { document.querySelectorAll("[data-role]").forEach((button) => button.addEventListener("click", () => { selectedRole = button.dataset.role; render(); })); document.getElementById("login-form")?.addEventListener("submit", login); document.getElementById("logout-button")?.addEventListener("click", () => { session = null; sessionStorage.removeItem(SESSION_KEY); phrase = []; view = "login"; render(); }); document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { if (button.dataset.patient) activePatientId = button.dataset.patient; view = button.dataset.view; render(); })); document.querySelectorAll("[data-category]").forEach((button) => button.addEventListener("click", () => { activeCategory = button.dataset.category; render(); })); document.querySelectorAll("[data-picto]").forEach((button) => button.addEventListener("click", () => { const item = pictograms.find((picto) => picto.id === button.dataset.picto); if (item) { phrase.push(item); announce(`${item.word} agregado a la frase`); render(); } })); document.querySelectorAll("[data-phrase-index]").forEach((button) => button.addEventListener("click", () => { phrase.splice(Number(button.dataset.phraseIndex), 1); render(); })); document.querySelectorAll("[data-complete]").forEach((button) => button.addEventListener("click", () => completeActivity(button.dataset.complete))); document.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", () => handleAction(button.dataset.action, button.dataset.board))); document.getElementById("patient-select")?.addEventListener("change", (event) => { activePatientId = event.target.value; render(); }); document.getElementById("comment-form")?.addEventListener("submit", saveComment); }
  function login(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const found = data.users.find((item) => item.email === form.get("email") && item.password === form.get("password") && item.role === selectedRole); if (!found) { document.getElementById("login-message").textContent = "No pudimos validar ese perfil. Revisá el rol, correo y clave."; return; } session = { userId: found.id, role: found.role, startedAt: new Date().toISOString() }; sessionStorage.setItem(SESSION_KEY, JSON.stringify(session)); view = found.role === "paciente" ? "comunicador" : "inicio"; activePatientId = found.role === "paciente" ? found.id : "pac-1"; render(); }
  function completeActivity(activityId) { const activity = data.activities.find((item) => item.id === activityId); if (!activity || !canAccessPatient(activity.patientId) || deliveryFor(activityId)) return; const origin = session.role === "familiar" ? "familiar" : "paciente"; data.deliveries.push({ id: `delivery-${Date.now()}`, activityId, patientId: activity.patientId, origin, completedAt: new Date().toISOString(), points: activity.points }); if (pointsFor(activity.patientId) >= 25 && !badgesFor(activity.patientId).some((badge) => badge.key === "primeros-pasos")) data.badges.push({ id: `badge-${Date.now()}`, patientId: activity.patientId, key: "primeros-pasos", label: "Primeros pasos" }); persist(); showToast(`Actividad completada: +${activity.points} puntos`); render(); }
  function saveComment(event) { event.preventDefault(); const text = document.getElementById("comment-text").value.trim(); if (!text || !canAccessPatient(activePatientId)) return; data.comments.push({ id: `comment-${Date.now()}`, patientId: activePatientId, authorId: session.userId, authorName: user().name, text, createdAt: new Date().toISOString() }); persist(); showToast("Comentario compartido con el profesional"); render(); }
  function handleAction(action, boardId) { if (action === "speak") speakPhrase(); if (action === "undo") { phrase.pop(); render(); } if (action === "clear-phrase") { phrase = []; render(); } if (action === "new-patient") openPatientModal(); if (action === "new-activity") openActivityModal(); if (action === "new-board") openBoardModal(); if (action === "edit-board") openBoardModal(boardId); }
  function speakPhrase() { const message = document.getElementById("speech-message"); if (!phrase.length) { message.textContent = "Primero elegí al menos un pictograma."; return; } const text = phrase.map((item) => item.word).join(" "); if (!("speechSynthesis" in window)) { message.textContent = "La reproducción no está disponible en este dispositivo. La frase sigue visible."; return; } window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = "es-AR"; utterance.onstart = () => { message.textContent = "Reproduciendo la frase en voz alta."; announce(message.textContent); }; utterance.onerror = () => { message.textContent = "No se pudo reproducir ahora. La frase sigue visible."; }; window.speechSynthesis.speak(utterance); }
  function modal(title, body) { const wrapper = document.createElement("div"); wrapper.className = "modal-backdrop"; wrapper.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">${title}</h2><button class="icon-button" data-close-modal aria-label="Cerrar">×</button></header>${body}</section>`; document.body.appendChild(wrapper); wrapper.querySelector("[data-close-modal]").addEventListener("click", () => wrapper.remove()); wrapper.addEventListener("click", (event) => { if (event.target === wrapper) wrapper.remove(); }); return wrapper; }
  function openPatientModal() { if (session.role !== "profesional") return; const dialog = modal("Registrar paciente", `<form id="patient-form" class="form-grid"><label>Nombre completo<input name="name" required minlength="2" /></label><label>Correo del paciente<input name="email" type="email" required /></label><label class="full">Correo del familiar vinculado<input name="familyEmail" type="email" placeholder="carla@decilo.test" /></label><p id="modal-message" class="message full" role="alert"></p><button class="primary-button full" type="submit">Crear y vincular paciente</button></form>`); dialog.querySelector("#patient-form").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name")).trim(); const email = String(form.get("email")).trim(); const familyEmail = String(form.get("familyEmail")).trim(); if (data.users.some((item) => item.email === email)) { dialog.querySelector("#modal-message").textContent = "Ese correo ya está registrado."; return; } const patient = { id: `pac-${Date.now()}`, name, email, role: "paciente", password: "decilo" }; const family = data.users.find((item) => item.email === familyEmail && item.role === "familiar"); data.users.push(patient); data.relationships.push({ professionalId: session.userId, patientId: patient.id, familyIds: family ? [family.id] : [] }); persist(); dialog.remove(); showToast("Paciente registrado y relación guardada"); render(); }); }
  function openActivityModal() { if (session.role !== "profesional") return; const patients = patientsForCurrentUser(); const dialog = modal("Asignar actividad", `<form id="activity-form" class="form-grid"><label>Paciente<select name="patientId">${patients.map((item) => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label>Puntos<input name="points" type="number" min="0" max="100" value="10" required /></label><label class="full">Título<input name="title" required minlength="3" /></label><label class="full">Instrucción<textarea name="instruction" required minlength="5"></textarea></label><label>Disponibilidad<select name="availability"><option>Hogar</option><option>Consulta</option></select></label><button class="primary-button full" type="submit">Confirmar asignación</button></form>`); dialog.querySelector("#activity-form").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); data.activities.push({ id: `activity-${Date.now()}`, patientId: form.get("patientId"), professionalId: session.userId, title: String(form.get("title")).trim(), instruction: String(form.get("instruction")).trim(), availability: form.get("availability"), points: Number(form.get("points")), status: "available" }); persist(); dialog.remove(); showToast("Actividad asignada"); render(); }); }
  function openBoardModal(boardId) { if (session.role !== "profesional") return; const existing = data.boards.find((item) => item.id === boardId); const patients = patientsForCurrentUser(); const dialog = modal(existing ? "Editar tablero" : "Nuevo tablero", `<form id="board-form" class="form-grid"><label>Paciente<select name="patientId">${patients.map((item) => `<option value="${item.id}" ${existing?.patientId === item.id ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join("")}</select></label><label class="full">Nombre del tablero<input name="name" value="${escapeHtml(existing?.name || "Tablero cotidiano")}" required /></label><fieldset class="full" style="border:0;padding:0"><legend class="eyebrow">Pictogramas disponibles</legend><div class="picto-grid">${pictograms.map((item) => `<label class="picto-tile"><input type="checkbox" name="pictograms" value="${item.id}" ${existing?.pictogramIds.includes(item.id) ? "checked" : ""} /><span class="symbol" aria-hidden="true">${item.symbol}</span><span class="word">${item.word}</span></label>`).join("")}</div></fieldset><button class="primary-button full" type="submit">Guardar tablero</button></form>`); dialog.querySelector("#board-form").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const pictogramIds = form.getAll("pictograms"); if (!pictogramIds.length) return; if (existing) Object.assign(existing, { patientId: form.get("patientId"), name: String(form.get("name")).trim(), pictogramIds }); else data.boards.push({ id: `board-${Date.now()}`, patientId: form.get("patientId"), professionalId: session.userId, name: String(form.get("name")).trim(), pictogramIds }); persist(); dialog.remove(); showToast("Tablero guardado en el orden seleccionado"); render(); }); }
  render();
})();