const { test, expect, uiLogin } = require('./fixtures');
const { createFamilyDemoService } = require('../family-demo');
test.use({ familyDemo:true });
test('monthly demo agenda persists profile, creates/cancels and clears patient/account data', async ({page,stack}) => {
  const u=stack.demoUsers,service=createFamilyDemoService(stack.db,stack.config.familyDemo);
  const invite=await service.invite(u.professional,u.patient1.id,{email:u.family.email});
  await service.accept(u.family,{code:invite.code});
  await uiLogin(page,stack,u.professional);
  await page.locator('.sidebar [data-view="pacientes"]').click();
  await page.getByLabel('Paciente activo').selectOption(String(u.patient1.id));
  await page.locator('#demo-profile').getByLabel('Nombre',{exact:true}).fill('Demo');
  await page.getByLabel('Apellido',{exact:true}).fill('Agenda');
  await page.getByRole('button',{name:'Guardar ficha'}).click();
  await expect(page.locator('#profile-status')).toContainText('guardada');
  await page.locator('.sidebar [data-view="agenda"]').click();
  await page.getByLabel('Fecha',{exact:true}).fill('2090-06-12');
  await page.getByLabel('Hora (Buenos Aires)').fill('10:00');
  await page.getByRole('button',{name:'Crear turno',exact:true}).click();
  await expect(page.locator('#agenda-list')).toContainText('10:00');
  await expect(page.locator('.agenda-calendar')).toContainText('1 turno');
  await page.getByLabel('Paciente activo').selectOption(String(u.patient2.id));
  await expect(page.locator('#agenda-list')).toContainText('No hay turnos');
  await page.getByLabel('Paciente activo').selectOption(String(u.patient1.id));
  await expect(page.locator('#agenda-list')).toContainText('pendiente');
  await page.locator('#logout-button').click();
  await uiLogin(page,stack,u.family);
  await page.locator('.sidebar [data-view="agenda"]').click();
  await page.getByLabel('Mes',{exact:true}).fill('2090-06');
  await expect(page.locator('#agenda-list')).toContainText('10:00');
  await expect(page.locator('#agenda-create')).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Cancelar turno'})).toHaveCount(0);
  await page.setViewportSize({width:360,height:780});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await service.revoke(u.professional,u.patient1.id,u.family.id);
  await page.reload();
  await expect(page.locator('#family-status')).toContainText('No tenés pacientes');
  await expect(page.locator('#agenda-list')).toHaveCount(0);
  await page.locator('#logout-button').click();
  await uiLogin(page,stack,u.patient1);
  await page.locator('.sidebar [data-view="agenda"]').click();
  await page.getByLabel('Mes',{exact:true}).fill('2090-06');
  await expect(page.locator('#agenda-list')).toContainText('pendiente');
  await expect(page.locator('#agenda-create')).toHaveCount(0);
  await page.locator('#logout-button').click();
  await uiLogin(page,stack,u.professional);
  await page.locator('.sidebar [data-view="pacientes"]').click();
  await page.getByLabel('Paciente activo').selectOption(String(u.patient1.id));
  await expect(page.locator('#demo-profile').getByLabel('Nombre',{exact:true})).toHaveValue('Demo');
  await page.locator('.sidebar [data-view="agenda"]').click();
  await page.getByLabel('Mes',{exact:true}).fill('2090-06');
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Cancelar turno'}).click();
  await expect(page.locator('#agenda-list')).toContainText('cancelado');
});
